### PR TITLE
$help command outputs all existing commands

### LINKED ISSUE #160: [BUG] The help command's output does not provide help for all commands currently available.
**Describe the bug**
Currently there is no description about promote & demote command in $help command.

**To Reproduce**

1. Type $help & enter
2. No desc about promote & demote command

**Expected behavior**
There should be description about this command

**Additional context**
For the description of command:
1. Promote: add admin for Listbot command. Note that owner of the server is automatically assigned the role admin of ListBot
2. Demote: remove admin from Listbot

**PS**: sorry for my bad english, if there is a better grammar or words for this, please do write those instead of this

### PR DESCRIPTION
**Pull request by Feelzor**
Closes #160 

This PR modifies the `$help` with the use of `fs` package, to read all existing files in `./src/commands`.

For each file, if a `name` and `description` property exist, the file is considered valid for a command and added to the array of printed help.

If the optional `usage` property exists, it is used to provide information on which arguments are expected for the command to be run properly.

The PR also modifies the different commands to add `usage` when necessary.

The result on local testing:
```bash
$add <element> = "Add an element to the list"
$clear = "Remove all element in the list for the specific channel."
$demote <@user> = "Remove a user from admin of ListBot"
$help = "Gets the bot commands"
$list = "Lists all the elements of the list"
$log = "Gets info from the bot"
$multi-add <element_1> <element_2> ... <element_n> = "Add multiple elements to the list"
$multi-remove <start_index> <end_index> = "Removes multiple elements from the list"
$ping = "Check the bot latency"
$poll <time_in_minutes> [nb_items=5] = "Generates a Poll from 2 to 9 random elements on the list"
$promote <@user> = "Promote a user into an admin of ListBot"
$random = "Gets a random element from the list"
$remind <time_in_seconds> = "Bot reminds of an item in channel after specific time"
$remove <index> = "Removes an element from the list"
```

### CODE REVIEW

File: src/commands/remind.js [hunk 1]
```diff
@@ -3,6 +3,7 @@ const Style = require('../utils/messageStyle.js')
 
 module.exports = {
     name: 'remind',
+    usage: '<time_in_seconds>',
```
Comment (rgroves) [inline src/commands/remind.js:6]: This looks like it's missing the reminder elements in the usage.

Should probably be something like `usage: '<time_in_seconds> [reminder_item [...]]'`

File: src/commands/help.js [hunk 2]
```diff
@@ -1,40 +1,31 @@
...
+            const command = require(`./${file}`)
+            if (
+                !Object.prototype.hasOwnProperty.call(command, 'name') ||
+                !Object.prototype.hasOwnProperty.call(command, 'description')
+            )
+                return
+
+            const usage = command.usage != null ? ` ${command.usage}` : ''
+            commands.push([`${command.name}${usage}`, command.description])
+        })
```
Comment (rgroves) [inline src/commands/help.js:28]: This is an good start, but it'd be a bit cleaner if help had a method to allow commands to register with help as they are loaded by the bot, instead of help having to have knowledge of the command files and having to require them to build the help.

**Review by rgroves — COMMENTED** [review]
This was already merged, but I made some comments to remind me to open a few issues for future fixes/enhancements.
