### PR TITLE
Send multiple messages if list is too long

### LINKED ISSUE #161: [BUG] $list outputs nothing if there are too many characters
**Describe the bug**
If the list is too long, the `$list` outputs nothing.

**To Reproduce**

1. Go to https://www.lipsum.com/
2. Generate and copy 1500 bytes of lorem ipsum
3. `$multi-add <paste_here>`
4. `$list`

**Expected behavior**
The bot should send multiple messages to show the entire list and avoid the 2k characters max.

### PR DESCRIPTION
**Pull request by Feelzor**
Closes #161 

This PR modifies the way `$list` work:
- Instead of using `map` to create the `fields` array, it iterates through the array
- Using a variable named `size` and a limit (set to 1800 to avoid problems, since the embed uses the channel name (max 100 characters) and the user name (max 32 characters) along with other data), we add lines to the embedded message
- If the current line makes the message grow over the limit, the message is sent **without** it, and the line is added in the next message

### CODE REVIEW

**Comment by Feelzor** [comment]
As a quick side note, it seems the bot hasn't been updated for a long time (the `$list` command doesn't have the same format as the one used by the bot currently), maybe would it be necessary to reboot it?

**Comment by rgroves** [comment]
Wondering if we should also add a max limit to `add` and `multi-add` to ensure that no single item is longer than a safe maximum. I believe there may be a current edge case that might not be treated correctly here. What if there is a single item in the list that when formatted is already over the `MAX_EMBED_SIZE`?

**Comment by Feelzor** [comment]
Indeed, having a max limit for a single item would help prevent the "single-item length" issue!

**Comment by rgroves** [comment]
Small bug in the behavior of the implementation provided (see below). If you can patch that up I'll merge this change.

Steps to reproduce:
1. Issue a clear command to start with a fresh empty list.
2. Use add or multi-add to add a single item that takes up the maximum length of a Discord message (2000 char max; this includes the command text; example of command to use provided below so you can copy/paste).

Example commands:
```
$clear
$add Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere consectetur pellentesque. Duis sodales scelerisque dolor sit amet facilisis. In hac habitasse platea dictumst. Suspendisse lacinia sagittis eros, a fermentum odio mollis a. Morbi sodales, lacus sed blandit fringilla, diam lectus ornare odio, vel malesuada purus justo at augue. Vivamus porta gravida orci. Maecenas euismod tortor a malesuada finibus. Aliquam erat volutpat. Maecenas rhoncus a purus at lacinia. Nullam vitae scelerisque justo. Donec diam magna, porta scelerisque bibendum sit amet, eleifend et dolor. Nunc ut volutpat dolor. Duis sodales diam vitae aliquet ultricies. Proin at nulla et mauris porta rhoncus. Nunc tincidunt vulputate porttitor. In faucibus purus hendrerit urna tincidunt luctus. Integer eu arcu massa. Sed dapibus neque nec neque vulputate commodo in quis nisl. Mauris non massa nisi. Etiam tincidunt condimentum dolor, sit amet feugiat purus lacinia sit amet. Quisque elementum vel lectus non laoreet. Curabitur risus dolor, volutpat vitae commodo eu, maximus a arcu. Aenean vehicula erat ac turpis faucibus vulputate. Nam vehicula sapien vestibulum, tristique nisi id, tincidunt augue. In at ornare eros. Nullam et elementum augue, vitae scelerisque arcu. Mauris at erat et ligula iaculis varius. Donec elit neque, gravida sit amet consequat et, feugiat eget felis. Nunc eget diam id orci elementum iaculis a a nulla. Maecenas sit amet tortor pulvinar purus tempus molestie ut sit amet diam. Fusce ex eros, molestie ultrices purus vitae, imperdiet hendrerit leo. Nunc pharetra velit et sapien gravida placerat. Suspendisse mattis turpis non ante tristique ultricies. Maecenas aliquam, magna pellentesque accumsan volutpat, libero ligula ullamcorper arcu, vel tempor tellus enim at ante. Vivamus sagittis est eros, id mollis orci molestie in. Nunc consequat mi nibh, sed tempus sapien tincidunt nec. Curabitur purus erat, tempus id feugiat ut, tempus eget turpis. Quisque aliquam lor velit
```

**Results**
The list command outputs two messages with the first being a message with just "md" in it (because of the empty markdown message it is trying to send it seems).

image
image

**Expected Results**
The list command should just output one message for the single item in the list:

image
image

File: src/commands/list.js [hunk 1]
```diff
@@ -25,16 +27,33 @@ module.exports = {
...
-            `List for \`${channelName}\``,
-            message.author,
-            '0xffff00',
-            Style.markDown(fields.join('\n'))
-        )
-        channel.send(embeddedMessage)
+        let fields = []
+        let size = 0
+
+        function send() {
```
Comment (rgroves) [inline src/commands/list.js:33]: Could just add a check up front here to avoid the behavior noted in the [comment here](https://github.com/tomassirio/ListBot/pull/165#issuecomment-749112895).
```
if (fields.length === 0) return
```

**Review by rgroves — CHANGES_REQUESTED** [review]

File: src/commands/list.js (hunk 1 above)
Comment (rgroves) [reply src/commands/list.js:33]: I popped in and added the check so I can get your changes merged. 

Thanks!

**Review by rgroves — APPROVED** [review]

**Review by rgroves — APPROVED** [review]
