### PR TITLE
Fix #147 empty arguments bug in 'add' and 'remove' commands

### LINKED ISSUE #147: [BUG] Issues with the Add, Remove and Multi-remove commands
1- Add command adds an empty string to the list if user doesn't provide any argument.
2- Remove command replies with "Successfully deleted item of index NaN" if user doesn't provide any argument.
3- Multi-remove command replies with "Successfully deleted items from index NaN to NaN".

### PR DESCRIPTION
**Pull request by vitasenka**
Closes #147 
- Fixed a bug when user calls "add", "multi-add", "remove" and "multi-remove" commands without providing enough arguments.
- Bot now replies with a usage hint if user calls any of the above commands incorrectly.

### CODE REVIEW

**Comment by rgroves** [comment]
Hi @vitasenka would you address the linting issues. You can use `npm run lint` locally to ensure you have no linting issues before performing your final push & PR. If you need input on any of the issues it's reporting please let me know and I'll provide guidance.

File: src/events/message.js [hunk 1]
```diff
@@ -1,15 +1,31 @@
...
     let args = message.content.slice(config.prefix.length).trim().split(/ +/)
-    const command = args.shift().toLowerCase()
+    const commandName = args.shift().toLowerCase()
 
-    if (!client.commands.has(command)) return
+    if (!client.commands.has(commandName)) return
+
+    const command = client.commands.get(commandName)
+
+    if (command.hasOwnProperty('min_args') && command.min_args > args.length) {
```
Comment (rgroves) [inline src/events/message.js]: Use the following instead of `command.hasOwnProperty('min_args')`:
```
Object.prototype.hasOwnProperty.call(command, 'min_args')
```

see: https://eslint.org/docs/rules/no-prototype-builtins

**Review by rgroves — CHANGES_REQUESTED** [review]
Please see review comments and address the linting issues. Also, if you haven't done so, please go through some manual testing of each action to ensure changes result in expected behavior for commands, both with correct usage and incorrect usage.
Thanks!

**Comment by vitasenka** [comment]
@rgroves fixed linting issues and tested commands manually.

**Review by rgroves — APPROVED** [review]
Looks good. 🥳
