### PR TITLE
Change argument delimiter for $multi-add command

### LINKED ISSUE #163: [BUG] Multi-add splits with spaces
**Describe the bug**
When you add elements with spaces, it considers them as different elements.

**To Reproduce**

1. `$multi-add Element 1 Element 2`
2. `Element`, `1`, `Element` and `2` are created.

**Expected behavior**
The bot should have a way to differenciate arguments even when they have spaces in them.
The use of semicolon as separator has been suggested on Discord.

I can create the fix with a new PR

### PR DESCRIPTION
**Pull request by Feelzor**
Closes #163 

This PR changes the way the commands work:
- The message splits at spaces
- First element is command name, the rest is joined again with `' '`, put into the `args` variable. At this point, we have two strings `commandName` and `args`
- It loads the command with the name, and then checks for its `delimiter` property. Using the `??` operator, the default fallback is `/ +/` (old delimiter).
- The multi-add command has `delimiter` set to `;`, the other commands don't have this property (it uses the fallback delimiter).

The PR updates the usage description of the `multi-add` command.

### CODE REVIEW

File: src/events/message.js [hunk 1]
```diff
@@ -5,12 +5,16 @@ const Util = require('../utils/utils')
 module.exports = async (client, message) => {
     if (!message.content.startsWith(config.prefix) || message.author.bot) return
 
-    let args = message.content.slice(config.prefix.length).trim().split(/ +/)
-    const commandName = args.shift().toLowerCase()
+    const splitMessage = message.content
+        .slice(config.prefix.length)
+        .trim()
+        .split(/ /)
+    let [commandName, args] = [splitMessage.shift(), splitMessage.join(' ')]
```
Comment (rgroves) [inline src/events/message.js:12]: Lost case-insensitivity for the command by not including the `.toLowerCase()` when destructuring the `commandName`.

File: src/commands/multi-add.js [hunk 2]
```diff
@@ -17,7 +18,7 @@ module.exports = {
 
         for (const instance of item) {
             let newItem = new Item({
-                content: instance,
+                content: instance.trim(),
```
Comment (rgroves) [inline src/commands/multi-add.js:21]: This trim() shouldn't be needed. See notes in message.js review.

File: src/commands/multi-add.js [hunk 3]
```diff
@@ -26,7 +27,9 @@ module.exports = {
 
         dbChannel.save()
 
-        const description = item.map((msg, i) => `${i + 1}. ${msg}`).join('\n')
+        const description = item
+            .map((msg, i) => `${i + 1}. ${msg.trim()}`)
```
Comment (rgroves) [inline src/commands/multi-add.js:31]: This trim() shouldn't be needed. See notes in message.js review.

File: src/events/message.js [hunk 4]
```diff
@@ -5,12 +5,16 @@ const Util = require('../utils/utils')
 module.exports = async (client, message) => {
     if (!message.content.startsWith(config.prefix) || message.author.bot) return
 
-    let args = message.content.slice(config.prefix.length).trim().split(/ +/)
-    const commandName = args.shift().toLowerCase()
+    const splitMessage = message.content
+        .slice(config.prefix.length)
+        .trim()
+        .split(/ /)
```
Comment (rgroves) [inline src/events/message.js:11]: Should be splitting by one or more spaces here as was done previously (`/ +/`) to remove extraneous spaces. Then on line 17 you can just split by a space and the multiple `trim` calls in multi-add.js become unnecessary.

File: src/commands/multi-add.js (hunk 2 above)
Comment (Feelzor) [reply src/commands/multi-add.js:21]: The thing is, without this trim, if we have `$multi-add Element1;    Element 2    ; Element 3`, we'll have space issues, since the separator is no longer space but `;`

File: src/commands/multi-add.js (hunk 3 above)
Comment (Feelzor) [reply src/commands/multi-add.js:31]: Same answer here than before

File: src/events/message.js (hunk 4 above)
Comment (Feelzor) [reply src/events/message.js:11]: I've only used one space in case having them was necessary for a future command. I wasn't sure if this was a great idea to keep the `/ +/` since we don't necessarily use the space separator for every command, but I don't see any context in which it would cause a problem. Changing it probably won't cost anything :)

Comment (rgroves) [reply src/events/message.js:11]: It won't cost anything for sure and will maintain previous behavior of the bot—leading spaces would not be treated as part of an item and they are now after this change. I've opened an issue so I won't forget about it and either someone else or myself can tackle it when they have time (it's breaking behavior, but certainly not critical).
